const PLAN_CATALOG = {
	free: {
		id: 'free',
		name: 'Starter',
		priceMonthlyCents: 0,
		displayPrice: 'Free',
		featureHighlights: [
			'1 workspace',
			'10 documents',
			'1000 document updates/month',
			'Basic editor',
			'Version history (7 days)',
			'Grammar checker (first 10 days)',
			'AI Assistant (first 10 days, 200 requests/month)',
			'Community support',
		],
		limits: {
			seats: 1,
			storageBytes: 1024 * 1024 * 1024,
			aiRequestsPerMonth: 200,
			collaborators: 2,
			documents: 10,
			documentUpdatesPerMonth: 1000,
			versionHistoryDays: 7,
			grammarAccessDays: 10,
			aiAccessDays: 10,
		},
	},
	pro: {
		id: 'pro',
		name: 'Pro',
		priceMonthlyCents: 1200,
		displayPrice: '$12/mo',
		featureHighlights: [
			'Unlimited workspaces',
			'Unlimited documents and updates',
			'AI Assistant',
			'AI usage up to 5000 requests/month',
			'Grammar checker',
			'Priority support',
			'Unlimited version history',
		],
		limits: {
			seats: 25,
			storageBytes: 20 * 1024 * 1024 * 1024,
			aiRequestsPerMonth: 5000,
			collaborators: 8,
			documents: null,
			documentUpdatesPerMonth: null,
			versionHistoryDays: null,
			grammarAccessDays: null,
			aiAccessDays: null,
		},
	},
	enterprise: {
		id: 'enterprise',
		name: 'Enterprise',
		priceMonthlyCents: 0,
		displayPrice: 'Custom',
		featureHighlights: [
			'SSO & SAML',
			'Custom roles & RBAC',
			'Audit logs',
			'Unlimited documents and updates',
			'Unlimited version history and grammar access',
			'AI usage up to 5000 requests/month',
			'SLA & dedicated support',
			'On-premise option',
		],
		limits: {
			seats: 500,
			storageBytes: 2 * 1024 * 1024 * 1024 * 1024,
			aiRequestsPerMonth: 5000,
			collaborators: 450,
			documents: null,
			documentUpdatesPerMonth: null,
			versionHistoryDays: null,
			grammarAccessDays: null,
			aiAccessDays: null,
		},
	},
	onprem: {
		id: 'onprem',
		name: 'Onprem',
		priceMonthlyCents: 0,
		displayPrice: 'Custom',
		featureHighlights: [
			'Self-hosted deployment',
			'Private network only',
			'Custom compliance controls',
			'Unlimited documents and updates',
			'Unlimited version history and grammar access',
			'AI usage up to 5000 requests/month',
			'Dedicated success team',
		],
		limits: {
			seats: 500,
			storageBytes: 2 * 1024 * 1024 * 1024 * 1024,
			aiRequestsPerMonth: 5000,
			collaborators: 450,
			documents: null,
			documentUpdatesPerMonth: null,
			versionHistoryDays: null,
			grammarAccessDays: null,
			aiAccessDays: null,
		},
	},
};

const TRIAL_DAYS_BY_PLAN = {
	pro: 14,
	enterprise: 30,
};

module.exports = {
	PLAN_CATALOG,
	TRIAL_DAYS_BY_PLAN,
};
