import type { ImageWrap, Run, RunFmt } from './textModel';

export type CursorFormat = RunFmt & {
  bullet: boolean;
  numberList: boolean;
  hasSpaceBeforeLine: boolean;
  hasSpaceAfterLine: boolean;
  imageSelected: boolean;
  imagePanelOpen: boolean;
  imageAlign: 'left' | 'center' | 'right';
  imageWidthPct: number;
  tableSelected: boolean;
  tablePanelOpen: boolean;
  tablePartialTextSelection: boolean;
};

export type RichEditorHandle = {
  getContent: () => string;
  setContent: (html: string) => void;
  setRuns: (runs: Run[]) => void;
  getFontSize: () => number;
  setFontSize: (n: number) => void;
  toggleBold: () => void;
  getBold: () => boolean;
  toggleItalic: () => void;
  getItalic: () => boolean;
  toggleUnderline: () => void;
  getUnderline: () => boolean;
  getFontFamily: () => string;
  setFontFamily: (f: string) => void;
  getTextColor: () => string;
  setTextColor: (c: string) => void;
  focus: () => void;
  toggleBullet: () => void;
  toggleNumberList: () => void;
  indentLeft: () => void;
  indentRight: () => void;
  setLineSpacing: (n: number) => void;
  toggleHighlight: () => void;
  setHighlightColor: (color: string | null) => void;
  insertLink: (label: string, url: string) => void;
  insertImage: (url: string) => void;
  insertTable: (rows: number, columns: number) => void;
  insertPageBreak: () => void;
  setImageAlign: (align: 'left' | 'center' | 'right') => void;
  setImageWidthPct: (widthPct: number) => void;
  setImageRotationDeg: (rotationDeg: number) => void;
  setImageWrap: (wrap: ImageWrap) => void;
  setImageAltText: (alt: string) => void;
  setImageFrontOpacityPct: (frontOpacityPct: number) => void;
  formatPainter: () => void;
  clearFormatting: () => void;
  toggleImagePanel: () => void;
  openImagePanel: () => void;
  closeImagePanel: () => void;
  toggleTablePanel: () => void;
  openTablePanel: () => void;
  closeTablePanel: () => void;
  toggleSpaceBeforeLine: () => void;
  toggleSpaceAfterLine: () => void;
  undo: () => void;
  redo: () => void;
};

export type ResizeHandle = 'n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w' | 'nw';
