-- AlterTable
ALTER TABLE "public"."plan_catalog" DROP COLUMN "featureHighlights",
DROP COLUMN "limits",
ADD COLUMN     "featureAiAssistant" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureAuditLogs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureBasicEditor" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureCommunitySupport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureCustomComplianceControls" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureCustomRolesRbac" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureDedicatedSuccessTeam" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureGrammarChecker" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureOnPremiseOption" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featurePrioritySupport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featurePrivateNetworkOnly" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureSelfHostedDeployment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureSlaDedicatedSupport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "featureSsoSaml" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "limitAiAccessDays" INTEGER,
ADD COLUMN     "limitAiRequestsPerMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "limitCollaborators" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "limitDocumentUpdatesPerMonth" INTEGER,
ADD COLUMN     "limitDocuments" INTEGER,
ADD COLUMN     "limitGrammarAccessDays" INTEGER,
ADD COLUMN     "limitSeats" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "limitStorageBytes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "limitVersionHistoryDays" INTEGER;

